sample.lo: /usr/lib/php5/20131226/sample/sample.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/usr/lib/php5/20131226/sample $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/lib/php5/20131226/sample/sample.c -o sample.lo 
$(phplibdir)/sample.la: ./sample.la
	$(LIBTOOL) --mode=install cp ./sample.la $(phplibdir)

./sample.la: $(shared_objects_sample) $(SAMPLE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sample) $(SAMPLE_SHARED_LIBADD)

